weasel:
  provider:
    refresh:
      web:
        enabled: true
      scheduled:
        enabled: true
        cron: 0 * * * *
        repositories:
          - file:///home/wes/Weasel/Provider/src/main/java
server:
  port: 9990